---
name: Create and publish the CV

on:
  push:
#    paths:
#      - CV
#    tags:
#      - 'v*.*.*'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Compile LaTeX document for german CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv_german.tex
          working_directory: "CV"
        env:
          TEXINPUTS: ".:./CV//:"

      - name: Compile LaTeX document for english CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv_english.tex
          working_directory: "CV"
        env:
          TEXINPUTS: ".:./CV//:"

      - name: Release
        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            CV/cv_german.pdf
            CV/cv_english.pdf